### ISSUE TITLE
Step 14_2 throws a error

### ISSUE THREAD

**Issue by RosaMGini** [ARS-toscana/Complex-script#8]
Step 14_2 thows teh following error

Errore: argomento non numerico trasformato in operatore binario

Looks like the reason is that study_entry_date_secondary_e is a character, and not a date, so the comparison

temp <- temp[date >= study_entry_date_secondary_e - 365 & date < study_entry_date_secondary_e, file:=1]

throws the error

The variable study_entry_date_secondary_e is created in 12_3 in risk_factors_min, row 79, and is a character ever since

**Comment by clobart** [comment]
Solved, adding a row in 12_3, because the problem was generated by study_entry_date_secondary_e not always filled

risk_factors_min<-risk_factors_min[,study_entry_date_secondary_e :=min(study_entry_date_secondary_e_risk,study_start,na.rm=T), by="person_id"][,-"study_entry_date_secondary_e_risk"]
